FROM golang:latest AS builder

WORKDIR /app

COPY . .

RUN go build -o /app/authorization-service/authorization

FROM scratch

COPY --from=builder /app/authorization-service/authorization /app/authorization-service/authorization

ENTRYPOINT [ "/app/authorization-service/authorization" ]